### ISSUE TITLE
How to replay an SGF game?

### ISSUE THREAD

**Issue by serd** [paviad/GoSharp#8]
Which methods should be used to jump to the next / previous nodes in an SGF game? Do I need to write new methods or is there built-in support to browse an SGF game?

**Comment by paviad** [comment]
I have no class that handles any kind of history in game.

**Comment by nerai** [comment]
@serd 

For reference, the standard does not contain anything like a history. It is relatively simple to create as additional properties, but that would be useless since the usual SGF viewers neither insert nor use these.

If you just want to display all variations in a systematic manner, it suffices to walk the tree in any order you like. Maybe something like this will help you:

```
IEnumerable<SGFNode> WalkNodes (IEnumerable<SGFGameTree> trees)
{
	foreach (var tree in trees) {
		foreach (var node in tree.Sequence.Nodes) {
			yield return node;
		}
		foreach (var node in WalkNodes (tree.GameTrees)) {
			yield return node;
		}
	}
}
```

You can use it like this:

```
void PrintAllComments (SGFCollection collection)
{
	foreach (var node in WalkNodes (collection.GameTrees)) {
		var c = node.Properties
			.Where (p => "c" == p.Name.ToLowerInvariant ())
			.FirstOrDefault ();
		if (c != null) {
			Console.WriteLine (c.Values[0].Value);
		}
	}
}
```
