### ISSUE TITLE
Get all unique groups

### ISSUE THREAD

**Issue by anpd03** [paviad/GoSharp#9]
Hi is there a way to get all unique groups on the board currently? From what I can see you need to check each point if it contains a group?

**Comment by paviad** [comment]
Apparently there is not. I guess there is no need for it for the purpose of playing a game, because you only need to know about groups when you play a stone, and then only about the groups touching that stone. What I do is I maintain a group cache so that I don't recalculate groups that I already did. But that's not what you want.

**Comment by anpd03** [comment]
To bad :) but will see what I can do on my own.
